In [ ]:
# Formação Cientista de Dados - Fernando Amaral e Jones Granatyr
# Qui Quadrado = provar que é apenas o acaso que ta variando

In [1]:
# Importação das funções, chi2_contingency porque temos 2 categorias
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
# Criação da matriz com os dados e execução do teste
novela = np.array([[19, 6], [43, 32]]) # 19 H assistem, 6 H não; 43 M assistem, 32 não
novela

array([[19,  6],
       [43, 32]])

In [3]:
#segundo valor é o pvalue
#Valor de p é maior que 0,05 não há evidências de diferença significativa (hipótese nula): não há diferença significativa, pode ser acaso
chi2_contingency(novela) # o que interessa é o segundo valor: 0.1534 = 15,34%; 

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

In [4]:
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [5]:
#agora valor de p menor que 0,05, podemos rejeitar a hipótese nula em favor da hipótese alternativa: há diferença significativa, nao é apenas acaso, o genero influencia
chi2_contingency(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))